using System; using System.Collections.Generic; using System.Linq; using System.Windows; using System.Windows.Controls; using Microsoft.EntityFrameworkCore; using UniversitySystem.Data; using UniversitySystem.Models;
namespace UniversitySystem.Controls{
public partial class CurriculumManagementControl : UserControl{
    private List<Curriculum> _curricula = new(); private List<Discipline> _disciplines = new(); private List<Group> _groups = new(); private Curriculum? _selected;
    public CurriculumManagementControl(){ InitializeComponent(); _ = LoadData(); }
    private async System.Threading.Tasks.Task LoadData(){ using var db = new AppDbContext(); _disciplines = await db.Disciplines.ToListAsync(); _groups = await db.Groups.ToListAsync(); _curricula = await db.Curricula.Include(c => c.Discipline).Include(c => c.Group).ToListAsync(); DisciplineComboBox.ItemsSource = _disciplines; GroupComboBox.ItemsSource = GroupFilter.ItemsSource = _groups; CurriculumDataGrid.ItemsSource = _curricula; }
    private void FilterChanged(object sender, object e){ var gid = (GroupFilter.SelectedItem as Group)?.Id; CurriculumDataGrid.ItemsSource = _curricula.Where(c => gid == null || c.GroupId == gid).ToList(); }
    private void AddCurriculum_Click(object sender, RoutedEventArgs e){ _selected = null; SemesterTextBox.Text = YearTextBox.Text = ""; DisciplineComboBox.SelectedIndex = -1; GroupComboBox.SelectedIndex = -1; }
    private void CurriculumDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e){ if (CurriculumDataGrid.SelectedItem is Curriculum c){ _selected = c; SemesterTextBox.Text = c.Semester.ToString(); YearTextBox.Text = c.AcademicYear; DisciplineComboBox.SelectedItem = _disciplines.FirstOrDefault(d => d.Id == c.DisciplineId); GroupComboBox.SelectedItem = _groups.FirstOrDefault(g => g.Id == c.GroupId); } }
    private async void SaveCurriculum_Click(object sender, RoutedEventArgs e){ if (DisciplineComboBox.SelectedItem == null || GroupComboBox.SelectedItem == null){ MessageBox.Show("Выберите дисциплину и группу"); return; } try{ using var db = new AppDbContext(); int sem = int.TryParse(SemesterTextBox.Text, out int s) ? s : 1; var did = (DisciplineComboBox.SelectedItem as Discipline)?.Id ?? 0; var gid = (GroupComboBox.SelectedItem as Group)?.Id ?? 0; var year = YearTextBox.Text.Trim(); if (_selected == null){ db.Curricula.Add(new Curriculum { DisciplineId = did, GroupId = gid, Semester = sem, AcademicYear = year }); } else { var c = await db.Curricula.FindAsync(_selected.Id); if (c != null){ c.DisciplineId = did; c.GroupId = gid; c.Semester = sem; c.AcademicYear = year; db.Update(c); } } await db.SaveChangesAsync(); await LoadData(); ClearForm(); MessageBox.Show("Сохранено"); } catch (Exception ex){ MessageBox.Show($"Ошибка: {ex.Message}"); } }
    private void CancelCurriculum_Click(object sender, RoutedEventArgs e) => ClearForm();
    private void ClearForm(){ _selected = null; SemesterTextBox.Text = YearTextBox.Text = ""; DisciplineComboBox.SelectedIndex = -1; GroupComboBox.SelectedIndex = -1; }}}
