using System; using System.Collections.Generic; using System.Linq; using System.Windows; using System.Windows.Controls; using Microsoft.EntityFrameworkCore; using UniversitySystem.Data; using UniversitySystem.Models;
namespace UniversitySystem.Controls{
public partial class DepartmentManagementControl : UserControl{
    private List<Department> _departments = new(); private List<Faculty> _faculties = new(); private Department? _selected;
    public DepartmentManagementControl(){ InitializeComponent(); _ = LoadData(); }
    private async System.Threading.Tasks.Task LoadData(){ using var db = new AppDbContext(); _faculties = await db.Faculties.ToListAsync(); _departments = await db.Departments.Include(d => d.Faculty).ToListAsync(); FacultyComboBox.ItemsSource = FacultyFilter.ItemsSource = _faculties; DepartmentDataGrid.ItemsSource = _departments; }
    private void FilterChanged(object sender, object e){ var fid = (FacultyFilter.SelectedItem as Faculty)?.Id; var q = SearchTextBox.Text.Trim().ToLower(); DepartmentDataGrid.ItemsSource = _departments.Where(d => (fid == null || d.FacultyId == fid) && (string.IsNullOrEmpty(q) || d.Name.ToLower().Contains(q))).ToList(); }
    private void AddDepartment_Click(object sender, RoutedEventArgs e){ _selected = null; DepartmentNameTextBox.Text = ""; FacultyComboBox.SelectedIndex = -1; }
    private void DepartmentDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e){ if (DepartmentDataGrid.SelectedItem is Department d){ _selected = d; DepartmentNameTextBox.Text = d.Name; FacultyComboBox.SelectedItem = _faculties.FirstOrDefault(f => f.Id == d.FacultyId); } }
    private async void SaveDepartment_Click(object sender, RoutedEventArgs e){ if (string.IsNullOrWhiteSpace(DepartmentNameTextBox.Text)){ MessageBox.Show("Введите название"); return; } try{ using var db = new AppDbContext(); var fid = (FacultyComboBox.SelectedItem as Faculty)?.Id ?? 0; if (_selected == null){ db.Departments.Add(new Department { Name = DepartmentNameTextBox.Text.Trim(), FacultyId = fid }); } else { var d = await db.Departments.FindAsync(_selected.Id); if (d != null){ d.Name = DepartmentNameTextBox.Text.Trim(); d.FacultyId = fid; db.Update(d); } } await db.SaveChangesAsync(); await LoadData(); DepartmentNameTextBox.Text = ""; FacultyComboBox.SelectedIndex = -1; _selected = null; MessageBox.Show("Сохранено"); } catch (Exception ex){ MessageBox.Show($"Ошибка: {ex.Message}"); } }
    private void ClearForm_Click(object sender, RoutedEventArgs e){ _selected = null; DepartmentNameTextBox.Text = ""; FacultyComboBox.SelectedIndex = -1; }}}
