using System; using System.Collections.Generic; using System.Linq; using System.Windows; using System.Windows.Controls; using Microsoft.EntityFrameworkCore; using UniversitySystem.Data; using UniversitySystem.Models;
namespace UniversitySystem.Controls{
public partial class GradeManagementControl : UserControl{
    private List<User> _students = new(); private List<Grade> _grades = new();
    public GradeManagementControl(){ InitializeComponent(); LoadFilters(); }
    private async void LoadFilters(){ using var db = new AppDbContext(); var groups = await db.Groups.ToListAsync(); var disciplines = await db.Disciplines.ToListAsync(); GroupComboBox.ItemsSource = groups; DisciplineComboBox.ItemsSource = disciplines; }
    private async void LoadGrades_Click(object sender, RoutedEventArgs e){ if (GroupComboBox.SelectedItem == null){ MessageBox.Show("Выберите группу"); return; } if (DisciplineComboBox.SelectedItem == null){ MessageBox.Show("Выберите дисциплину"); return; } try{ using var db = new AppDbContext(); int gid = (GroupComboBox.SelectedItem as Group)?.Id ?? 0; int did = (DisciplineComboBox.SelectedItem as Discipline)?.Id ?? 0; _students = await db.Users.Where(u => u.GroupId == gid && u.Role == "Student").ToListAsync(); _grades = await db.Grades.Where(g => g.DisciplineId == did && _students.Select(s => s.Id).Contains(g.StudentId)).ToListAsync(); var data = _students.Select(s => new { s.Id, s.FullName, s.Role, TempGrade = _grades.FirstOrDefault(g => g.StudentId == s.Id)?.Value.ToString() ?? "" }).ToList(); GradesDataGrid.ItemsSource = data; } catch (Exception ex){ MessageBox.Show($"Ошибка: {ex.Message}"); } }
    private async void SaveGrades_Click(object sender, RoutedEventArgs e){ try{ using var db = new AppDbContext(); int did = (DisciplineComboBox.SelectedItem as Discipline)?.Id ?? 0; var semStr = (SemesterCombo.SelectedItem as ComboBoxItem)?.Content?.ToString(); int sem = int.TryParse(semStr, out int s) ? s : 1; string year = YearTextBox.Text.Trim(); string type = ExamRadio.IsChecked == true ? "Exam" : SeminarRadio.IsChecked == true ? "Seminar" : "Lab"; foreach (var st in _students){ var row = GradesDataGrid.Items.Cast<object>().FirstOrDefault(i => i.GetType().GetProperty("Id")?.GetValue(i)?.Equals(st.Id) == true); if (row != null){ var gradeProp = row.GetType().GetProperty("TempGrade"); var gradeStr = gradeProp?.GetValue(row)?.ToString(); if (decimal.TryParse(gradeStr, out decimal val) && val >= 2 && val <= 5){ var existing = await db.Grades.FirstOrDefaultAsync(g => g.StudentId == st.Id && g.DisciplineId == did && g.Type == type && g.Semester == sem && g.AcademicYear == year); if (existing != null){ existing.Value = val; existing.Date = DateTime.UtcNow; db.Update(existing); } else { db.Grades.Add(new Grade { StudentId = st.Id, DisciplineId = did, Type = type, Value = val, Semester = sem, AcademicYear = year, Date = DateTime.UtcNow }); } } } } await db.SaveChangesAsync(); MessageBox.Show("Оценки сохранены"); } catch (Exception ex){ MessageBox.Show($"Ошибка: {ex.Message}"); } }
    private void GroupChanged(object sender, SelectionChangedEventArgs e){ }}}
