using System; using System.Collections.Generic; using System.Linq; using System.Windows; using System.Windows.Controls; using Microsoft.EntityFrameworkCore; using UniversitySystem.Data; using UniversitySystem.Models;
namespace UniversitySystem.Controls{
public partial class UserManagementControl : UserControl{
    private List<User> _users = new(); private List<Group> _groups = new(); private User? _selected; private bool _isInitialized;
    public UserManagementControl(){ InitializeComponent(); _isInitialized = true; _ = LoadData(); }
    private async System.Threading.Tasks.Task LoadData(){ using var db = new AppDbContext(); _groups = await db.Groups.ToListAsync(); _users = await db.Users.Include(u => u.Group).ToListAsync(); GroupComboBox.ItemsSource = GroupFilter.ItemsSource = _groups; UserDataGrid.ItemsSource = _users; }
    private void FilterChanged(object sender, object e){ if (!_isInitialized || _users == null || UserDataGrid == null) return; try { var q = SearchTextBox.Text?.Trim()?.ToLower() ?? ""; var role = (RoleFilter.SelectedItem as ComboBoxItem)?.Content?.ToString(); var gid = (GroupFilter.SelectedItem as Group)?.Id; UserDataGrid.ItemsSource = _users.Where(u => (string.IsNullOrEmpty(q) || (u.FullName?.ToLower().Contains(q) ?? false) || (u.Login?.ToLower().Contains(q) ?? false)) && (role == null || role == "Все" || u.Role == role) && (gid == null || u.GroupId == gid)).ToList(); } catch { /* Ignore errors during initialization */ } }
    private void AddUser_Click(object sender, RoutedEventArgs e){ _selected = null; LoginTextBox.Text = PasswordBox.Password = FullNameTextBox.Text = ""; RoleComboBox.SelectedIndex = -1; GroupComboBox.SelectedIndex = -1; }
    private void UserDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e){ if (UserDataGrid.SelectedItem is User u){ _selected = u; LoginTextBox.Text = u.Login; FullNameTextBox.Text = u.FullName; RoleComboBox.SelectedItem = RoleComboBox.Items.Cast<ComboBoxItem>().FirstOrDefault(i => i.Content?.ToString() == u.Role); GroupComboBox.SelectedItem = _groups.FirstOrDefault(g => g.Id == u.GroupId); } }
    private async void SaveUser_Click(object sender, RoutedEventArgs e){ if (string.IsNullOrWhiteSpace(LoginTextBox.Text) || string.IsNullOrWhiteSpace(FullNameTextBox.Text)){ MessageBox.Show("Заполните обязательные поля"); return; } try{ using var db = new AppDbContext(); var role = (RoleComboBox.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "Student"; var gid = (GroupComboBox.SelectedItem as Group)?.Id; if (_selected == null){ if (string.IsNullOrWhiteSpace(PasswordBox.Password)){ MessageBox.Show("Введите пароль"); return; } db.Users.Add(new User { Login = LoginTextBox.Text.Trim(), Password = PasswordBox.Password, FullName = FullNameTextBox.Text.Trim(), Role = role, GroupId = gid ?? 0 }); } else { var u = await db.Users.FindAsync(_selected.Id); if (u != null){ u.Login = LoginTextBox.Text.Trim(); if (!string.IsNullOrWhiteSpace(PasswordBox.Password)) u.Password = PasswordBox.Password; u.FullName = FullNameTextBox.Text.Trim(); u.Role = role; u.GroupId = gid ?? 0; db.Update(u); } } await db.SaveChangesAsync(); await LoadData(); ClearForm(); MessageBox.Show("Сохранено"); } catch (Exception ex){ MessageBox.Show($"Ошибка: {ex.Message}"); } }
    private void CancelUser_Click(object sender, RoutedEventArgs e) => ClearForm();
    private void ClearForm(){ _selected = null; LoginTextBox.Text = PasswordBox.Password = FullNameTextBox.Text = ""; RoleComboBox.SelectedIndex = -1; GroupComboBox.SelectedIndex = -1; }}}
